name: "Metric"
on:
  push:
    # run on pushes to main
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: onlineboutique    # Add your cluster name here.
  GKE_ZONE: us-central1-b   # Add your cluster zone here.
  DEPLOYMENT_NAME: onlineboutique # Add your deployment name here.
  IMAGE: static-site
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@v2
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        GKE_CLUSTER: onlineboutique    # Add your cluster name here.
        GKE_ZONE: us-central1-b   # Add your cluster zone here.
        DEPLOYMENT_NAME: onlineboutique # Add your deployment name here.
        IMAGE: static-site
      with:
        args: apply -f packaging/k8s/manifests/ -n staging



