name: "Metrics"
on:
  push:
    # run on pushes to main
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: onlineboutique    # Add your cluster name here.
  GKE_ZONE: us-central1-b   # Add your cluster zone here.
  DEPLOYMENT_NAME: onlineboutique # Add your deployment name here.
  IMAGE: static-site
  
jobs:
  push-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        # Set up kustomize
    - name: Deploy
      run: |
        kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
        kubectl get nodes


